version: '3.8'

services:
  app:
    image: node:17.4.0-alpine3.14
    environment:
      NODE_ENV: development
    ports:
      - "3000:3000"
    command: npm run dev
    depends_on:
      - mysql
    volumes:
      - ./../:/app
    working_dir: /app
  mysql:
    container_name: mysql_db
    image: mysql:5.6
    environment:
      - MYSQL_DATABASE=nodejs
      - MYSQL_ROOT_PASSWORD=niznik
      - MYSQL_USER=konrad
      - MYSQL_PASSWORD=niznik
      - MYSQL_ROOT_HOST=localhost
    ports:
      - "3306:3306"
    volumes:
      - "./../../data/mysql:/var/lib/mysql"
